[package]
name = "pictoascii"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pictoascii"
crate-type = ["cdylib"]

[dependencies]
image = "0.25.1"
imageproc = "0.25.0"
pyo3 = "0.20.0"
